import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({comments}) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <table className={styles.table} >
        <tr className={styles.row} >
          <th>Id</th>
          <th>Name</th>
          <th>Email</th>
        </tr>
        {
          comments.map((comment) => {
            return (
              <tr key={comment.id} >
                <td>{comment.id}</td>
                <td>{comment.name}</td>
                <td>{comment.email}</td>
              </tr>
            )
          })
        }


      </table>
    </>
  )
}

export async function getStaticProps() {


  const fetchComments = await fetch('https://jsonplaceholder.typicode.com/posts/1/comments')
  const data = await fetchComments.json()

  return {
    props: {
      comments: data
    }
  }
}